config/routes.rb
StorycafeSimple::Application.routes.draw do
  get "stories/change_status" 
  devise_for :users
  resources :stories , :groups , :projects
  get "logs/mark_read"
  root :to => 'stories#index'

end

app/models/story.rb
# -*- coding: utf-8 -*-
class Story
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  field :user, type: String
  field :title, type: String
  field :description, type: String
  belongs_to :group
  belongs_to :user
  auto_increment :list_id,:seed => 0, :collection => "story_list_ids"
  field :current_status, type: String , default: "new"
  field :next_status, type: String , default: "started"

  def self.add_story params_story
    create!(params_story)
  end

  def self.get_stories_by_group_id id
   Rails.configuration.status.inject({}) do |result,s|
     result.merge(Hash[s.to_sym,get_stories_by_groupid_and_currentstatus(id,s)])
   end
  end

  # get default stories of public group
  def self.get_default_stories
    Group.get_default_group.stories
  end

  def self.get_default_story
    Group.get_default_group.stories.first
  end

  def self.get_story_by_story_id id
    find(id)
  end

  # id : story_id
  # status : current_status
  def self.set_story_status id,current_status,next_status
    where(_id: id).find_and_modify({"$set" => { current_status: current_status,
                                                 next_status: next_status
                                              }},new: true)
  end

  def self.get_stories_by_groupid_and_currentstatus id,status
    where(group_id: id,current_status: status)
  end

  def self.set_description id,des
    Story.where(_id: id).find_and_modify({"$set"=> {description: des}},new: true)  
  end
end

app/controllers/stories_controller.rb
# -*- coding: utf-8 -*-
class StoriesController < ApplicationController

  before_filter :authenticate_user!
  def index
    render "index"
  end

  def create
   #  log = Log.new_message "#{current_user.email} create a story of '#{params[:story][:title]}'"
     #用调用方法的形式不可用
     #publish_message("messages/new",log)
  #   PrivatePub.publish_to("/channels/#{session[:current_project].id}", message: log)

     new_length = Story.get_stories_by_group_id(session[:current_group].id)[:new].length
     story   = session[:current_story] =  Story.add_story(params[:story])
     new_length == 0 ? respond_to_html(:_stories_in_status, {resource: [story],type: "new"})
                               : respond_to_html(:_every_story_in_table, {story: story})
  end

  def edit
    session[:current_story] = Story.get_story_by_story_id(params[:id]) if params[:id] != session[:current_story].id
    respond_to_html(:_description,{:meta => { :type => "story"}})
  end

  # put/:id def update
  def update
    session[:current_story] = Story.set_description(params[:id],params[:description])
    # to_json 不知道何时不加
    render :json => "autosave success!".to_json
  end

   # change status of story
   # params[:status] stand for next status
   def change_status
     next_status = get_next_status(params[:next_status])
     next_length = Story.get_stories_by_group_id(session[:current_group].id)[params[:next_status].to_sym].length
     # log = Log.new_message "#{story.title} be to #{params[:status]} by #{current_user.email}"
     # PrivatePub.publish_to(get_channel_path, message: log)
     story = Story.set_story_status(params[:story_id],params[:next_status],next_status)
     next_length != 0 ? respond_to_html(:_every_story_in_table,{story: story})
                                                      : respond_to_html(:_stories_in_status,{resource: [story],type: params[:next_status]})
   end
end

app/helpers/stories_helper.rb
module StoriesHelper
  def current_story
    p "==============================="
    p session[:current_story]
    session[:current_story]
  end


  def current_storys
     Story.get_stories_by_group_id session[:current_group].id
  end

  def get_story_status number
    %w[new started review finished][number-1]
  end

  def get_story_status_title type
   type=="new" ? "new stories" :
   type=="started" ? "stories is beginning" :
   type=="review" ? "completed wait participant to review" : "finished and closed"

  end

  def get_story_next_status next_status
    next_status==2 ? "stories_started" :
    next_status==3 ? "stories_review" : "stories_finished"

  end

end

app/views/stories/_description.html.slim
.content
  - if meta[:type]=="group"
    - if current_group
      .span12.nav
        h4
          span.icon-th.span1
          span.span10 = current_group.title
          span.span1.icon-cog
      .span12
        = form_for current_group ,:method =>"put",:remote => true,:html => {:id => "description_todo","data-type" => "json"} do |f|
          textarea( placeholder="#{t('story.description')}" id="todo-description-areatext" name="group[description]")
            = current_group.description
        .span12
          i.span5.icon-user  Byronlee
        .span12
          i.span7.icon-calendar =  current_group.created_at
  - else
   - if current_story
     .span12.nav
       h4
         span.icon-th.span1
         span.span10 = current_story.title
         span.span1.icon-cog
     .row-fluid
       .span12
         .row-fluid
           .span12
             = form_for current_story , :method =>"put", :remote => true ,:html => {:id => "description_todo",:'data-type' => "json"} do |f|
                 textarea( placeholder="#{t('story.description')}" id="todo-description-areatext" name="description" )
                   =  current_story.description
             .span12
               i.span5.icon-user  Byronlee
             .span12
               i.span7.icon-flag  assigned to public
             .span12
               i.span7.icon-calendar = current_group.created_at

app/views/stories/_every_story_in_table.html.slim
- if current_story&&current_story.id ==="#{story.id}"
  tr.active
    td.span1.story-id
      span.badge.badge-inverse = story.list_id
    td.span2 = get_user_name_by_user_id(story.user_id)
    td.span8 = link_to story.title ,edit_story_path(story) ,:remote => true, :method => :get,:class=> "every-story"
    td.span1
      = link_to_if((story.current_status != "finished") , button_tag("", :type => 'button',  :class =>"icon-fast-forward change_status"),"/stories/change_status?story_id=#{story.id}&next_status=#{story.next_status}",:class =>"change_status_icon",:title =>"标记进入#{story.next_status}状态", :remote => true , :attr_next_status => story.next_status ) do  content_tag(:span,"" ,:class=>"icon-lock") end

- else
  tr
    td.span1.test_id
      span.badge = story.list_id
    td.span2 = get_user_name_by_user_id(story.user_id)
    td.span8 = link_to story.title ,edit_story_path(story) ,:remote => true, :method => :get,:class=> "every-story"

    td.span1
      = link_to_if((story.current_status != "finished") , button_tag("", :type => 'button',  :class =>"icon-fast-forward change_status"),"/stories/change_status?story_id=#{story.id}&next_status=#{story.next_status}",:class =>"change_status_icon",:title =>"标记进入#{story.next_status}状态", :remote => true , :attr_next_status => story.next_status ) do  content_tag(:span,"" ,:class=>"icon-lock") end

app/views/stories/_form_new_story.html.slim
= form_for( Story.new , :remote => true ) do |f|
  = f.text_field :title, :class => "span4",:placeholder => "快速添加故事"
  = f.hidden_field :user_id , :value =>  "#{current_member}"
  = f.hidden_field :description , :value => ""
  = f.hidden_field :group_id , :value =>  "#{current_group.id}"
  = f.submit  "新建故事",:disable_with => "请稍等..", :class => "btn btn-inverse publish"
x

app/views/stories/_group.html.slim
div.span2.slide-left
  .side-iterations
    .nav-iterations
      span Iterations
    .all-iterations
      - if resource
        ul.span12
          -  resource.each do |s|
            - if current_group && current_group.id ==="#{s.id}"
              li.active
                = link_to s.title ,edit_group_path(s) , :method => :get
            -else
              li
                = link_to s.title ,edit_group_path(s) , :method => :get
  .side-participants
    .nav-participants
      span Participants
    .all-participants

app/views/stories/_stories_in_status.html.slim
.content
  - if resource && !resource.empty?
    .span12.nav
      h4
        span.span1 = resource.length
        span.span11 = get_story_status_title(type)
    table.span12
      - resource.each do |story|
        = render "stories/every_story_in_table" , :story => story
  - else
    .span12.nav
      h4
        span.span1 = 0
        span.span11 = get_story_status_title(type)
    .no_content
      .content
        p
          i.icon-pencil  There are no storys with status #{type} in this Iteration  ！
          i.icon-edit    Fill in the blanks and click the new story button in the navigation bar.

app/views/stories/_todo.html.slim
.content
  .span12.nav
    h4
      span.icon-list.span1
      span.span10 All TODO in this Iteration
      span.span1.icon-cog
  .span12
    = form_for current_group ,:method =>"put",:remote => true,:html => {:id => "description_todo","data-type" => "json"} do |f|
      textarea( placeholder="#{t('story.description')}" id="todo-description-areatext" name="group[todo]")
        = current_group.todo
      .span12
        i.icon-calendar  
        span &nbsp;Last updated:2012-12-15 22:59:50 

app/views/stories/index.html.slim
= render "stories/group"   , :resource => current_groups
.span10.slide-right
  .block-stories-new
    = render "stories/stories_in_status", :resource => current_storys[:new] , :type=> "new"
  .block-stories-started
    = render "stories/stories_in_status", :resource => current_storys[:started],:type=> "started"
  .block-story-description
    = render "stories/description" ,  :meta => { :type => "story"}
  .block-stories-review
    = render "stories/stories_in_status", :resource => current_storys[:review],:type=> "review"
  .block-stories-finished
    = render "stories/stories_in_status", :resource => current_storys[:finished],:type=> "finished"
  .block-story-todo
    = render "stories/todo"